# Folders/data structure.
root_folder: ../../EXTERNAL/cfp/kaggle_dr  # root folder of image data
ids_file: ../../EXTERNAL/cfp/kaggle_dr/ids.lst  # image identity file, list of image file names w/o file extension (e.g. jpg, png)
data_folder: raw
file_extension_data_in: png

image_folder: cfp_224 # folder to save preprocessed images
mask_folder: masks  # folder to save circle masks
file_extension_data_out: png  # avoid image compression as with jpeg
minimal_save: False  # if True only saves non-background pixels and ratios to reconstruct image masks 

# Preprocessing parameters.
resize_shape: 224  # square target shape after preprocessing: (resize_shape, resize_shape)
remove_rectangles: True  # remove little rectangles (marker for image rotation) on fundus images 
resize_canny_edge: 1000  # resize image for canny edge detection (scales bad with image size)
sigma_scale: 50  # scale for sigma parameter of canny edge detection
circle_fit_steps: 100  # number of steps for circle fitting
Î»: 0.01  # decay constant of exponential function
fit_largest_contour: True  # if True only fit circle to the largest contour, helpful with noise like text on the image


parallel_processing: True
num_workers_reverse: 4 # all but 4 cpus via "os.cpu_count() - 4"